# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b677bd52d46b5c01188365a06329ce17eb17c7b0cd93644a945177ff93d677fd786ab0b3fd6c2742a257d05834b28d1712e34118566e7afb75442e998a8c3b03

test:
  secret_key_base: 70a58f063fe83170bda07c6e75373a79739401751aa09fcb3852c56f920646a91f3448ac8779e9e4499cbcbd649931757544a549071d288842de7bda19d140fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
